export { default as Chart } from "@/components/icons/IconChart.vue"
export { default as Chevron } from "@/components/icons/IconChevron.vue"
export { default as Fb } from "@/components/icons/IconFb.vue"
export { default as Github } from "@/components/icons/IconGithub.vue"
export { default as Ig } from "@/components/icons/IconIg.vue"
export { default as Linkedin } from "@/components/icons/IconLinkedin.vue"
export { default as Mail } from "@/components/icons/IconMail.vue"
export { default as Phone } from "@/components/icons/IconPhone.vue"
export { default as User } from "@/components/icons/IconUser.vue"
export { default as X} from "@/components/icons/IconX.vue"